export const COUNTRY_TO_ISO: Record<string, string> = {
  Argentina: "AR",
  "United States": "US",
  Canada: "CA",
  Mexico: "MX",
  Brazil: "BR",
  Chile: "CL",
  Colombia: "CO",
  Perú: "PE",
  Ecuador: "EC",
  Venezuela: "VE",
  Uruguay: "UY",
  Paraguay: "PY",
  Bolivia: "BO",
  Panama: "PA",
  "Costa Rica": "CR",
  Guatemala: "GT",
  Honduras: "HN",
  "El Salvador": "SV",
  Nicaragua: "NI",
  "Dominican Republic": "DO",
  Cuba: "CU",
  Jamaica: "JM",
  Haiti: "HT",
  "Trinidad and Tobago": "TT",
  Barbados: "BB",
  Bahamas: "BS",
  Belize: "BZ",
  Guyana: "GY",
  Suriname: "SR",
  "Antigua and Barbuda": "AG",
  Dominica: "DM",
  Grenada: "GD",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "United Kingdom": "GB",
  France: "FR",
  Germany: "DE",
  Italy: "IT",
  Spain: "ES",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  Austria: "AT",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Finland: "FI",
  Poland: "PL",
  Portugal: "PT",
  Greece: "GR",
  Ireland: "IE",
  "Czech Republic (Czechia)": "CZ",
  Romania: "RO",
  Hungary: "HU",
  Bulgaria: "BG",
  Croatia: "HR",
  Slovakia: "SK",
  Slovenia: "SI",
  Estonia: "EE",
  Latvia: "LV",
  Lithuania: "LT",
  Luxembourg: "LU",
  Cyprus: "CY",
  Russia: "RU",
  Ukraine: "UA",
  Belarus: "BY",
  Moldova: "MD",
  Georgia: "GE",
  Armenia: "AM",
  Azerbaijan: "AZ",
  Kazakhstan: "KZ",
  Uzbekistan: "UZ",
  Turkey: "TR",
  Israel: "IL",
  "Saudi Arabia": "SA",
  "United Arab Emirates": "AE",
  Qatar: "QA",
  Kuwait: "KW",
  Bahrain: "BH",
  Oman: "OM",
  Jordan: "JO",
  Lebanon: "LB",
  Iraq: "IQ",
  Iran: "IR",
  Afghanistan: "AF",
  Pakistan: "PK",
  India: "IN",
  Bangladesh: "BD",
  "Sri Lanka": "LK",
  Nepal: "NP",
  Bhutan: "BT",
  "Myanmar (Burma)": "MM",
  Thailand: "TH",
  Vietnam: "VN",
  Cambodia: "KH",
  Laos: "LA",
  Malaysia: "MY",
  Singapore: "SG",
  Indonesia: "ID",
  Philippines: "PH",
  Brunei: "BN",
  China: "CN",
  Japan: "JP",
  "South Korea": "KR",
  "North Korea": "KP",
  Taiwan: "TW",
  Mongolia: "MN",
  Australia: "AU",
  "New Zealand": "NZ",
  Fiji: "FJ",
  "Papua New Guinea": "PG",
  "South Africa": "ZA",
  Egypt: "EG",
  Nigeria: "NG",
  Kenya: "KE",
  Ethiopia: "ET",
  Ghana: "GH",
  Tanzania: "TZ",
  Uganda: "UG",
  Morocco: "MA",
  Algeria: "DZ",
  Tunisia: "TN",
  Libya: "LY",
  Sudan: "SD",
  Angola: "AO",
  Mozambique: "MZ",
  Madagascar: "MG",
  Cameroon: "CM",
  "Ivory Coast (Côte d'Ivoire)": "CI",
  Senegal: "SN",
  Mali: "ML",
  "Burkina Faso": "BF",
  Niger: "NE",
  Chad: "TD",
  Guinea: "GN",
  "Sierra Leone": "SL",
  Liberia: "LR",
  Togo: "TG",
  Benin: "BJ",
  Mauritania: "MR",
  Gambia: "GM",
  "Guinea-Bissau": "GW",
  Gabon: "GA",
  "Equatorial Guinea": "GQ",
  "Congo (Congo-Brazzaville)": "CG",
  "Democratic Republic of the Congo (Congo-Kinshasa)": "CD",
  "Central African Republic": "CF",
  Rwanda: "RW",
  Burundi: "BI",
  Eritrea: "ER",
  Djibouti: "DJ",
  Somalia: "SO",
  "Eswatini (Swaziland)": "SZ",
  Lesotho: "LS",
  Botswana: "BW",
  Namibia: "NA",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  Malawi: "MW",
  Mauritius: "MU",
  Seychelles: "SC",
  Comoros: "KM",
  "Cabo Verde": "CV",
  "São Tomé and Príncipe": "ST",
  Yemen: "YE",
  Syria: "SY",
  Palestine: "PS",
  Iceland: "IS",
  Liechtenstein: "LI",
  Monaco: "MC",
  "San Marino": "SM",
  "Vatican City": "VA",
  Andorra: "AD",
  Malta: "MT",
  Albania: "AL",
  "North Macedonia": "MK",
  "Bosnia and Herzegovina": "BA",
  Serbia: "RS",
  Montenegro: "ME",
  Kosovo: "XK",
  Kyrgyzstan: "KG",
  Tajikistan: "TJ",
  Turkmenistan: "TM",
  Maldives: "MV",
  "Timor-Leste": "TL",
  Kiribati: "KI",
  "Marshall Islands": "MH",
  Micronesia: "FM",
  Nauru: "NR",
  Palau: "PW",
  Samoa: "WS",
  "Solomon Islands": "SB",
  Tonga: "TO",
  Tuvalu: "TV",
  Vanuatu: "VU",
};
